# URL's
GOOGLE_HOMEPAGE = "https://www.google.com"
YOUTUBE_HOMEPAGE = "https://www.youtube.com"

# ASSISTANT SETTINGS
PAUSE_THRESHOLD  = 0.5
ENERGY_THRESHOLD = 2000

# OWNER SETTINGS
OWNER_NAME = "Schuyler"
